#:schema node_modules/wrangler/config-schema.json
name = "hack-week-ts"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public/"
binding = "ASSETS"
experimental_serve_directly = false

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[r2_buckets]]
bucket_name = "hack-week"
binding = "HACK_WEEK_BUCKET"

[ai]
binding = "AI"

[[workflows]]
name = "analyze-image"
binding = "ANALYZE_IMAGE"
class_name = "AnalyzeImage"

[[durable_objects.bindings]]
name = "ANALYZER_STORE"
class_name = "AnalyzerStore"

[[migrations]]
tag = "v1"                      # Should be unique for each entry
new_classes = ["AnalyzerStore"] # Array of new classes
